--DROP PK
IF EXISTS (SELECT TOP 1 1 
			FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
			WHERE  CONSTRAINT_TYPE = 'PRIMARY KEY'
				AND TABLE_NAME = 'Product' 
				AND TABLE_SCHEMA ='dbo' )
BEGIN
      ALTER TABLE [dbo].[Product] DROP CONSTRAINT PK_Product
END 
GO

-- ADD PK
ALTER TABLE [dbo].[Product] ADD CONSTRAINT PK_Product PRIMARY KEY CLUSTERED (Id)
GO